### ISSUE TITLE
Bug in username ban logic.

### ISSUE THREAD

**Issue by akhamuliak** [WebentwicklerAt/typo3-loginlimit#2]
If you have set `basic.disableIpCheck ` setting and wan't to ban users by username only there is an issue.

First time user is banned for time which is set in `basic.bantime` field. Let's name it `user1`

 Ban is called in UserAuthentication.php Hook at line 91.

```
$loginAttempts = $this->getLoginAttemptRepository()->countLoginAttemptsByUsername($username, $this->settings['findtime']['value']);
if ($loginAttempts >= $this->settings['maxretry']['value']) {
       //bug here
	$this->ban('', $username);
}
```
So it's set to ban with empty $ip argument and insert ban record to DB with empty `ip` field.

After that if another used (`user2`) need to be banned it fails inside of `ban` function, because it checks if `ban` record already exists and `$ip` is also empty there as in previous case. So it returns the previously saved record and update ban time for first user.

```
	protected function ban($ip, $username) {
		$ban = $this->getBanRepository()->findBan($ip, $username);
// $ban will be != NULL here.
		if ($ban === NULL) {
			$ban = $this->objectManager->get('WebentwicklerAt\\Loginlimit\\Domain\\Model\\Ban');
			$ban->setIp($ip);
			$ban->setUsername($username);

			$this->getBanRepository()->add($ban);
		}
		else {
			$ban->setTstamp(new \DateTime('@' . $GLOBALS['EXEC_TIME']));
			$this->getBanRepository()->update($ban);
		}

		$this->getPersistenceManager()->persistAll();
	}
```

So.. ban time is updated for `user1` and `user2` is not added to `tx_loginlimit_domain_model_ban` at all.

This is caused by findBan() method in BanRepository.

```
	/**
	 * Finds first ban based on IP or username
	 *
	 * @param string $ip
	 * @param string $username
	 * @return object
	 */
	public function findBan($ip, $username) {
		$query = $this->createQuery();
		$constraints = $query->logicalOr(
	//BUG here
	         	$query->equals('ip', $ip),
			$query->equals('username', $username)
		);

		$result = $query->matching($constraints)->setLimit(1)->execute();

        return $result->getFirst();
	}
```
If $ip is empty `$query->equals('ip', $ip)` is always matched `user1` record, as it already is in database with empty `ip` field.  Same for `findActiveBan` function.

It's hard to notice because `user2` is still forbidden to login or.. Banned is some case.

Login attempts check is still valid in that case and continue counting.

``` UserAuthentication.php Hook line 90.
if ($loginAttempts >= $this->settings['maxretry']['value']) 
```

So... user is banned but not for ban time from `basic.bantime` it's banned for `basic.findtime` value or in other words till login times counter will not be cleared for that user.

**Comment by leitgab** [comment]
There is no feature/setting `basic.disableIpCheck` at all. So I don't know what you are talking about.

**Comment by akhamuliak** [comment]
Oops... Sorry, I didn't realize that it was related to fork, and I wasn't using an original repository.
